const CONFIG = {
  SHEETS: {
    DEVICES: "DEVICES",
    COMMANDS: "COMMANDS",
    RESULTS: "RESULTS",
    LOGS: "LOGS"
  },

  CONTROLLER_TOKEN: "GANTI_CONTROLLER_TOKEN",
  WORKER_TOKEN: "GANTI_WORKER_TOKEN",

  ONLINE_THRESHOLD_SECONDS: 120,
  DEFAULT_COMMAND_EXPIRE_MINUTES: 5
};
